#!/bin/sh

install_all() {
	install_turbo
}

# Quit with error message
die() {
	echo "$@"
	exit 1
}

# Slowdown data flow (10 characters/s)
slow() {
	sed 's/./&\n/g; s/$/ENTER/' | while read c
	do
		if [ "$c" = "ENTER" ]
		then
			echo
		else
			printf "%c" "$c"
		fi
		sleep 0.1
	done
}

# Turbo PASCAL 3.01A for CP/M-80
install_turbo() {


	# Download & extract archive file
	ZIP=TP_301A.ZIP
	[ -f $ZIP ] || wget http://www.retroarchive.org/cpm/lang/$ZIP
	unzip -Lf $ZIP -d tmp
	cd tmp && {

		# Run instalation program
		# [S]creen instalation, [6]:ANSI Terminal
		# [N]o terminal modifications, [8]MHz
		# [Q]uit
		cat <<-EOF | slow | tnylpo tinst.com
			s6
			n8
			q
		EOF

		chmod a+x turbo.com
		cp -v turbo.com turbo.msg turbo.ovr ../..
	}

	rm -fr tmp
}

# Remove turbo
remove_turbo() {
	rm -v turbo.com turbo.msg turbo.ovr
}

mkdir -p dist
cd dist || die "No instalation directory (dist)"
"${1:-install_all}" "$2"
