#!/bin/sh
# Commandline wrapper for:
# Turbo PASCAL 3.01A for CP/M-80
# by 2021 Andrzej Borsuk

# Utility script
# Quit with error message
die() {
	echo "$@"
	exit 1
}

# Utility script
# Slowdown data flow (10 characters/s)
slow() {
	sed 's/./&\n/g; s/$/ENTER/' | while read c
	do
		if [ "$c" = "ENTER" ]
		then
			echo
		else
			printf "%c" "$c"
		fi
		sleep 0.1
	done
}

# MAIN

FILE=${1:?FILE?}

[ -f "$FILE" ] || FILE="$FILE.pas"
[ -f "$FILE" ] || die "No file $FILE"

# Compile file using turbo.com
cat <<-EOF | slow | tnylpo turbo.com
	yocq
	c${1}
	q
EOF

printf "\033[m"
chmod -v a+x "${FILE%.pas}.com"
